package com.devteria.identity_service.enums;

public enum EventLog {
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    USER_SOFT_DELETED,
    GROUP_CREATED,
    GROUP_UPDATED,
    GROUP_DELETED,
    GROUP_MEMBER_ADDED,
    GROUP_MEMBER_REMOVED,
    GROUP_SOFT_DELETED,
    TICKET_CREATED,
    TICKET_UPDATED,
    TICKET_DELETED,
    USER_ADDED_TO_GROUP,
    USER_REMOVED_FROM_GROUP,
    USER_RESTORED,
    USER_RESTORED_TO_GROUP
}
